### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by antoniov** [OCA/maintainer-quality-tools#261]
I am running mainteiner-quality-tools in local.
New version, after upgrade flake8, pep8 and plynt crashes with follow message:
======== Testing test_pylint ========
Traceback (most recent call last):
  File "/opt/openerp/dev/maintainer-quality-tools/travis/test_pylint", line 11, in <module>
    import run_pylint
  File "/opt/openerp/dev/maintainer-quality-tools/travis/run_pylint.py", line 10, in <module>
    import pylint.lint
  File "/usr/lib/python2.6/site-packages/pylint/lint.py", line 642
    control_pragmas = {'disable', 'enable'}
                                ^
SyntaxError: invalid syntax

Enviroment:
CentOS 6.5 - python 2.6.6

**Comment by pedrobaeza** [comment]
The problem is clearly in your pylint version mismatch, because you're running in python 2.6, and you need 2.7.

**Comment by antoniov** [comment]
Thanks
