### ISSUE TITLE
ir_attachment: IOError [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#299]
```bash
2015-11-24 16:13:45,078 23051 INFO openerp_test openerp.addons.base.ir.ir_attachment: _read_file reading /home/travis/.local/share/Odoo/filestore/openerp_test/58/58fd4f74ff005d177019f05fa0a5fad6562b5fcf
Traceback (most recent call last):
File "/home/travis/odoo-9.0/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/travis/.local/share/Odoo/filestore/openerp_test/58/58fd4f74ff005d177019f05fa0a5fad6562b5fcf'
2015-11-24 16:13:45,079 23051 INFO openerp_test openerp.addons.base.ir.ir_attachment: _read_file reading /home/travis/.local/share/Odoo/filestore/openerp_test/d6/d6c84c13589b2232842fdbb26d2c476c52075227
Traceback (most recent call last):
File "/home/travis/odoo-9.0/openerp/addons/base/ir/ir_attachment.py", line 151, in _file_read
r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/travis/.local/share/Odoo/filestore/openerp_test/d6/d6c84c13589b2232842fdbb26d2c476c52075227'
```
https://travis-ci.org/OCA/maintainer-quality-tools/jobs/92966636#L299-L307

This is because the restore of database need a additional copy of the filestore `/home/travis/.local/share/Odoo/filestore/openerp_template/` to `/home/travis/.local/share/Odoo/filestore/openerp_test/`

**Comment by dreispt** [comment]
I've also noticed this error in my local machine using plain Odoo 9.
I do use a db template to speedup dropdb/createdb/enable tests cycles...

**Comment by moylop260** [comment]
FYI fixed here: https://github.com/OCA/maintainer-quality-tools/pull/304

**Comment by atulrajdutta** [comment]
provide the custom-addons path along with addons path in configuration file
$vim /etc/odoo11.conf

addons_path = /opt/odoo/odoo11/addons,/opt/odoo/odoo11/custom_addons
