### ISSUE TITLE
How to run `test_pylint` standalone?

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#394]
I'm doing some work on MQT and want to be able to run pylint directly from the terminal.
I'm stuck with a `click.exceptions.MissingParameter: None` error, and I wonder if @moylop260 could point me in the right direction.

I'm running:
```
$ export VERSION="8.0"
$ ./test_pylint
Traceback (most recent call last):
  File "./test_pylint", line 177, in <module>
    ] + extra_params_cmd, standalone_mode=False)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1390, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1675, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1365, in full_process_value
    raise MissingParameter(ctx=ctx, param=self)
click.exceptions.MissingParameter: None
```

Thanks!

**Comment by pedrobaeza** [comment]
Why don't you use https://github.com/OCA/maintainer-quality-tools/tree/master/git? 

This is the executable needed: https://github.com/OCA/maintainer-quality-tools/blob/master/git/pre-commit

**Comment by jcdrubay** [comment]
You can call directly from the folder containing the `.git`:
`TRAVIS_PULL_REQUEST="true" TRAVIS_BRANCH="HEAD" TRAVIS_BUILD_DIR=`pwd -P` .git/hooks/test_pylint`

**Comment by dreispt** [comment]
Yes, it would be nice for `test_pylint` to use `TRAVIS_BUILD_DIR` if available, and only if not fall back to the current working directory.
That should be a simple fix - do you want to try it?

**Comment by jcdrubay** [comment]
I ll be very happy to help :)
