### ISSUE TITLE
All lint checks in OCA repositories are failling

### ISSUE THREAD

**Issue by lreficent** [OCA/maintainer-quality-tools#589]
See example: https://travis-ci.org/OCA/knowledge/jobs/499733258

```
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/test_pylint", line 59, in <module>
    result = run_pylint.pylint_run(is_pull_request, version, git_work_dir)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 168, in pylint_run
    real_errors = main(cmd, standalone_mode=False)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 308, in main
    extra_params=extra_params)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 278, in run_pylint
    pylint_res = pylint.lint.Run(cmd, exit=False)
TypeError: __init__() got an unexpected keyword argument 'exit'
+=======================================
|  Tests summary:
|---------------------------------------
| test_flake8                 Success
| test_pylint                 FAIL
+=======================================
The command "travis_run_tests" exited with 1.
```

**Comment by pedrobaeza** [comment]
This can be due to a new version of depending libraries. It seems there's a PR for adding compatibility for this:

https://github.com/OCA/pylint-odoo/pull/239

**Comment by pedrobaeza** [comment]
Maybe we can freeze requirements meanwhile. @moylop260 what do you think?

**Comment by pedrobaeza** [comment]
Fixed through https://github.com/OCA/pylint-odoo/pull/240 and with a direct commit here 0bc455037f0cade2e951a55b91b6409170ab648f for mitigating this ASAP.

**Comment by lreficent** [comment]
Thanks
