### ISSUE TITLE
pre-commit prettier environment fails when prebuilding node (13.12.0)

### ISSUE THREAD

**Issue by HviorForgeFlow** [OCA/maintainer-quality-tools#661]
### Environment
Ubuntu 18.04.4 LTS
Python 3.6.9 running ona  virtualenv
pre-commit 2.2.0

### Error message
```
[INFO] Installing environment for https://github.com/prettier/prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/home/hvior/odoo/venvs/13.0/bin/python3', '-mnodeenv', '--prebuilt', '--clean-src', '/home/hvior/.cache/pre-commit/repomqxmxlfw/node_env-default')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
     * Install prebuilt node (13.12.0) .
    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/hvior/odoo/venvs/13.0/lib/python3.6/site-packages/nodeenv.py", line 1517, in <module>
        main()
      File "/home/hvior/odoo/venvs/13.0/lib/python3.6/site-packages/nodeenv.py", line 1113, in main
        create_environment(env_dir, opt)
      File "/home/hvior/odoo/venvs/13.0/lib/python3.6/site-packages/nodeenv.py", line 936, in create_environment
        install_node(env_dir, src_dir, opt)
      File "/home/hvior/odoo/venvs/13.0/lib/python3.6/site-packages/nodeenv.py", line 700, in install_node
        install_node_wrapped(env_dir, src_dir, opt)
      File "/home/hvior/odoo/venvs/13.0/lib/python3.6/site-packages/nodeenv.py", line 723, in install_node_wrapped
        download_node_src(node_url, src_dir, opt, prefix)
      File "/home/hvior/odoo/venvs/13.0/lib/python3.6/site-packages/nodeenv.py", line 552, in download_node_src
        dl_contents = io.BytesIO(urlopen(node_url).read())
      File "/usr/lib/python3.6/http/client.py", line 472, in read
        s = self._safe_read(self.length)
      File "/usr/lib/python3.6/http/client.py", line 624, in _safe_read
        raise IncompleteRead(b''.join(s), amt)
    http.client.IncompleteRead: IncompleteRead(16432905 bytes read, 16910427 more expected)
```

**Comment by pedrobaeza** [comment]
I had the same problem in https://github.com/OCA/sale-workflow/pull/1025

I finally merge manually, but I was puzzled why was happening.

**Comment by HviorForgeFlow** [comment]
I hope this is a temporary issue, I was also getting 500 errors on that request.

**Comment by HviorForgeFlow** [comment]
Error seems to be solved, I've just been able to create prettier environment, so closing.
