### ISSUE TITLE
pre-commit incompatible libraries

### ISSUE THREAD

**Issue by HviorForgeFlow** [OCA/maintainer-quality-tools#663]
Since https://github.com/pre-commit/mirrors-pylint/commit/ed254b0d23ad3b2ef9a8ba2bbdd963de2502a265 was introduced it is not possible to update pre-commit. By default it is installing pylint==2.5.x and pylint-odoo is using 2.3.2 which is compatible with pylint-plugin-utils 0.5 but 2.5.x is not. https://github.com/PyCQA/pylint-plugin-utils/pull/16

I can't figure out why runbot is not failing, it should be feed by cache.

IMO OCA should have more control over this changes.

@sbidoul @pedrobaeza @moylop260

**Comment by sbidoul** [comment]
@HviorForgeFlow do you have an example where it fails?
We normally pin the pylint version like [this](https://github.com/OCA/mis-builder/blob/a3f61d54c4f5a2a3693777182f3aa56b3e12d428/.pre-commit-config.yaml#L73-L74).

**Comment by HviorForgeFlow** [comment]
For example, I drop /home/<user>/.cache/pre-commit on my local environment.
I take purchase-workflow repo and run pre-commit.
```
pylint with optional checks..............................................Failed
- hook id: pylint
- duration: 1.34s
- exit code: 1

Traceback (most recent call last):
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 3, in <module>
    from pylint.utils import UnknownMessage
ImportError: cannot import name 'UnknownMessage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint/lint/run.py", line 303, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint/lint/pylinter.py", line 498, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/astroid/modutils.py", line 202, in load_module_from_name
    return load_module_from_modpath(dotted_name.split("."), path, use_sys)
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/astroid/modutils.py", line 245, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/usr/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint_odoo/__init__.py", line 3, in <module>
    from . augmentations.main import apply_augmentations
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint_odoo/augmentations/__init__.py", line 1, in <module>
    from . import main
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint_odoo/augmentations/main.py", line 4, in <module>
    from pylint_plugin_utils import suppress_message
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 5, in <module>
    from pylint.utils import UnknownMessageError as UnknownMessage
ImportError: cannot import name 'UnknownMessageError'
Traceback (most recent call last):
  File "/home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/lib/python3.6/site-packages/pylint_plugin_utils/__init__.py", line 3, in <module>
    from pylint.utils import UnknownMessage
ImportError: cannot import name 'UnknownMessage'
```

```
hvior@hvior-ThinkPad-E570 ~/o/a/a/O/purchase-workflow (13.0-fix-purchase_open_quantity) [1]> /home/hvior/.cache/pre-commit/repob5vb5uo2/py_env-python3/bin/python -m pip freeze
astroid==2.2.0
docutils==0.14
isort==4.3.4
lazy-object-proxy==1.4.3
lxml==4.5.0
mccabe==0.6.1
pre-commit-dummy-package==0.0.0
Pygments==2.2.0
pylint==2.5.2
pylint-odoo==3.1.0
pylint-plugin-utils==0.5
restructuredtext-lint==1.1.3
rfc3986==1.4.0
six==1.14.0
toml==0.10.0
typed-ast==1.2.0
whichcraft==0.6.1
wrapt==1.12.1
```

**Comment by HviorForgeFlow** [comment]
My fault, I was using pre-commit autoupdate which is updating all libraries without restriction

**Comment by vancouver29** [comment]
I also had this error after running `pre-commit autoupdate`. How did you fix it?

**Comment by sbidoul** [comment]
Each pylint-odoo version requires a very precise version of pylint. If you run pre-commit auto-update it updates the pylint version but not the pylint-odoo version. So these must be managed manually.

![image](https://user-images.githubusercontent.com/692075/182329567-a88cc438-ce33-4304-a499-ca31113dcbae.png)

**Comment by moylop260** [comment]
FYI you can use the pre-commit hook of pylint-odoo directly instead
 - https://github.com/OCA/pylint-odoo/pull/368

You can check the version from tags:
 - https://github.com/OCA/pylint-odoo/tags

**Comment by sbidoul** [comment]
@moylop260 that's a great news, thanks. I was preparing to reopen https://github.com/OCA/pylint-odoo/issues/246 :)
