### ISSUE TITLE
Adapting MQT test script to GitHub actions, issue with travis_makepot

### ISSUE THREAD

**Issue by GSLabIt** [OCA/maintainer-quality-tools#681]
Hi all, 

i'm trying to adapt MQT test script used in Travis to GitHub Actions. I've been able to make LINT and TEST working but no way for `travis_makepot`. 

For some reason it get stuck at: 

https://github.com/OCA/maintainer-quality-tools/blob/c9864146f4ee19dd5a7c7bf5a0ea7001ff4700cd/travis/travis_makepot#L69-L74

Error:
```
2020-12-04T20:16:15.4953300Z Using db openerp_test to generate .pot
2020-12-04T20:16:15.4954251Z fatal: not in a git directory
2020-12-04T20:16:15.4960871Z Traceback (most recent call last):
2020-12-04T20:16:15.4962652Z   File "/github/home/maintainer-quality-tools/travis/travis_makepot", line 127, in <module>
2020-12-04T20:16:15.4968455Z     exit(main(database=database))
2020-12-04T20:16:15.4970277Z   File "/github/home/maintainer-quality-tools/travis/travis_makepot", line 70, in main
2020-12-04T20:16:15.4972341Z     'git', 'config', 'user.name', os.environ['GITHUB_USER'],
2020-12-04T20:16:15.4973674Z   File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
2020-12-04T20:16:15.4975132Z     raise CalledProcessError(retcode, cmd)
2020-12-04T20:16:15.4977103Z subprocess.CalledProcessError: Command '['git', 'config', 'user.name', 'gslabit']' returned non-zero exit status 128.

```

`subprocess` not executing `git` command properly, maybe `git command` not found?

Any hint on how to fix ?

**Comment by moylop260** [comment]
```diff
- ['git', 'config', 'user.name', 'gslabit']
+ ['git', 'config', '--global', 'user.name', 'gslabit']
```

**Comment by GSLabIt** [comment]
@moylop260 thx for the hint, that solved the issue. 

Actually same error seems happening while `click-odoo-makepot` tryes to add file back to the repo.
```
2020-12-05 00:45:20,605 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/server-tools 
2020-12-05 00:45:20,789 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/server-ux 
2020-12-05 00:45:20,901 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/stock-logistics-barcode 
2020-12-05 00:45:20,975 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/stock-logistics-warehouse 
2020-12-05 00:45:21,269 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/stock-logistics-workflow 
2020-12-05 00:45:21,432 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/storage 
2020-12-05 00:45:21,478 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/timesheet 
2020-12-05 00:45:21,651 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/web 
2020-12-05 00:45:21,880 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/dependencies/website 
2020-12-05 00:45:21,970 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/odoo-12.0/addons 
2020-12-05 00:45:22,826 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/odoo-12.0/odoo/addons 
2020-12-05 00:45:22,886 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/odoo-12.0/odoo/osv 
2020-12-05 00:45:22,888 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/odoo-12.0/odoo/report 
2020-12-05 00:45:22,888 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/odoo-12.0/odoo/modules 
2020-12-05 00:45:22,890 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/odoo-12.0/odoo/service 
2020-12-05 00:45:22,892 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/odoo-12.0/odoo/tools 
2020-12-05 00:45:22,901 1190 DEBUG openerp_test odoo.tools.translate: Scanning files of modules at /github/home/odoo-12.0/odoo 
fatal: Not a git repository (or any parent up to mount point /__w)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2020-12-05 00:45:22,928 1190 INFO openerp_test odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections to 'sslmode=prefer dbname=openerp_test' 
2020-12-05 00:45:22,929 1190 ERROR openerp_test click_odoo.env_options: exception 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/click_odoo/env_options.py", line 214, in _invoke
    return self.org_invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click_odoo_contrib/makepot.py", line 165, in main
    purge_old_translations,
  File "/usr/local/lib/python3.6/site-packages/click_odoo_contrib/makepot.py", line 94, in export_pot
    cwd=addons_dir,
  File "/usr/local/lib/python3.6/site-packages/click_odoo_contrib/gitutils.py", line 11, in commit_if_needed
    subprocess.check_call(cmd, cwd=cwd)
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'add', '-f', '--', '/__w/ooops-release/ooops-release/base_location_italian_cities_import/i18n/base_location_italian_cities_import.pot', '/__w/ooops-release/ooops-release/base_location_italian_cities_import/i18n/it.po']' returned non-zero exit status 128.
Error: Command '['git', 'add', '-f', '--', '/__w/ooops-release/ooops-release/base_location_italian_cities_import/i18n/base_location_italian_cities_import.pot', '/__w/ooops-release/ooops-release/base_location_italian_cities_import/i18n/it.po']' returned non-zero exit status 128.
```
any hint in how to fix this one?

thx

**Comment by moylop260** [comment]
It is safer adding `--git-dir` and `--work-tree` instead of `cwd` for `git` commands.

I mean,

`git --git-dir=PATH_GIT/.git --work-tree=PATH_GIT add -f -- PATH_GIT/SUBPATH_FILE`

`PATH_GIT` must be a real `git clone REPO PATH_GIT` result.

**Comment by moylop260** [comment]
Could you share the repository and the output URL where you are testing this, please?

**Comment by GSLabIt** [comment]
> It is safer adding `--git-dir` and `--work-tree` instead of `cwd` for `git` commands.
> 
> I mean,
> 
> `git --git-dir=PATH_GIT/.git --work-tree=PATH_GIT add -f -- PATH_GIT/SUBPATH_FILE`
> 
> `PATH_GIT` must be a real `git clone REPO PATH_GIT` result.

Script is using `click-odoo-makepot` to export .pot files and installed by pip, it should be changed in click-odoo-contrib repo isn't it?

**Comment by GSLabIt** [comment]
> Could you share the repository and the output URL where you are testing this, please?

docker image repo used in workflow: https://github.com/GSLabIt/gha-oca-mqt

fork maintainer-quality-tools: https://github.com/GSLabIt/maintainer-quality-tools/tree/ooops-makepot

test repo: https://github.com/GSLabIt/test-actions

**Comment by GSLabIt** [comment]
found the issue, it was related to git version in docker. Using `3.6-slim-buster image` solved the issue.
